apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: distribuidos
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http

---

apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: distribuidos
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http

---

apiVersion: v1
kind: Service
metadata:
  name: log-message-processor
  namespace: distribuidos
spec:
  selector:
    app: log-message-processor
  ports:
    - protocol: TCP
      port: 6029
      targetPort: 6029
      name: http

  
---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: distribuidos
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      name: http
  
---

apiVersion: v1
kind: Service
metadata:
  name: todos-api
  namespace: distribuidos
spec:
  selector:
    app: todos-api
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: http

---

apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: distribuidos
spec:
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      name: http
  